//user

export const USER_STATE_SAVE ='USER_STATE_SAVE'


// location
export const ADD_TO_CURRENT_LOCATION = 'ADD_TO_CURRENT_LOCATION';
export const ADD_TO_CURRENT_CORDINATE = 'ADD_TO_CURRENT_CORDINATE';

// SCREEN
export const ADD_TO_CURRENT_SCREEN = 'ADD_TO_CURRENT_SCREEN';

//USER LOG IN
export const USER_LOGIN_REGUEST = 'USER_LOGIN_REGUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_REGISTRATION_REGUEST = 'USER_REGISTRATION_REGUEST'
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const SHIPPING_COST = 'SHIPPING_COST'