export const ordersData = [
    {
      orderId: 'GM2D36-51',
      status: 'Pending',
      date: 'Thus 25, Jun 2022',
      totallItems: 15,
      grandTotall: 3560,
      deliveryTime: 'Jun 25 -  06:30PM',
      deliveryLocation:
        'Harvest Group, DITF Bangladesh 14 Pavilion Golen, Dhaka-1212',
      orderItems: [
        {
          id: 1,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/today-pick-for-you/coolRanch.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 2,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/breakfast.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 3,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 4,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
      ],
      orderView: [
        {
          id: 1,
          type: 'confirmed',
          status: true,
        },
        {
          id: 2,
          type: 'processing',
          status: true,
        },
        {
          id: 3,
          type: 'packed',
          status: true,
        },
        {
          id: 4,
          type: 'shipped',
          status: true,
        },
        {
          id: 5,
          type: 'delivered',
          status: true,
        },
      ],
      orderTrack: [
        {
          id: 1,
          title: 'Order Delivered',
          subTitle: 'Enjoy your product!',
          time: 11.15,
          status: true,
        },
        {
          id: 2,
          title: 'Order Dispatched',
          subTitle: 'Contact Rider',
          time: 11.1,
          status: true,
        },
        {
          id: 3,
          title: 'Order Confirmed',
          subTitle: 'Awaiting confirmation',
          time: 11.1,
          status: true,
        },
        {
          id: 4,
          title: 'Order Placed',
          subTitle: 'Thank you for ordering',
          time: 10.04,
          status: true,
        },
        // {
        //   id: 5,
        //   title: 'Order Placed',
        //   subTitle: 'We have received your order',
        //   time: 10.04,
        //   status: true,
        // },
      ],
    },
    {
      orderId: 'GM2D36-52',
      status: 'Cancelled',
      date: 'Thus 25, Jun 2022',
      totallItems: 15,
      grandTotall: 3560,
      deliveryTime: 'Jun 25 -  06:30PM',
      deliveryLocation:
        'Harvest Group, DITF Bangladesh 14 Pavilion Golen, Dhaka-1212',
      orderItems: [
        {
          id: 1,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/today-pick-for-you/coolRanch.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 2,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/breakfast.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 3,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 4,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
      ],
      orderView: [
        {
          id: 1,
          type: 'confirmed',
          status: true,
        },
        {
          id: 2,
          type: 'processing',
          status: false,
        },
        {
          id: 3,
          type: 'packed',
          status: false,
        },
        {
          id: 4,
          type: 'shipped',
          status: false,
        },
        {
          id: 5,
          type: 'delivered',
          status: false,
        },
      ],
      orderTrack: [
        {
          id: 1,
          title: 'Order Delivered',
          subTitle: 'Enjoy your product!',
          time: 11.15,
          status: true,
        },
        {
          id: 2,
          title: 'Order Dispatched',
          subTitle: 'Contact Rider',
          time: 11.1,
          status: true,
        },
        {
          id: 3,
          title: 'Order Confirmed',
          subTitle: 'Awaiting confirmation',
          time: 11.1,
          status: true,
        },
        {
          id: 4,
          title: 'Order Placed',
          subTitle: 'Thank you for ordering',
          time: 10.04,
          status: true,
        },
        // {
        //   id: 5,
        //   title: 'Order Placed',
        //   subTitle: 'We have received your order',
        //   time: 10.04,
        //   status: true,
        // },
      ],
    },
    {
      orderId: 'GM2D36-53',
      status: 'Processing',
      date: 'Thus 25, Jun 2022',
      totallItems: 15,
      grandTotall: 3560,
      deliveryTime: 'Jun 25 -  06:30PM',
      deliveryLocation:
        'Harvest Group, DITF Bangladesh 14 Pavilion Golen, Dhaka-1212',
      orderItems: [
        {
          id: 1,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/today-pick-for-you/coolRanch.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 2,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/breakfast.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 3,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 4,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
      ],
      orderView: [
        {
          id: 1,
          type: 'confirmed',
          status: true,
        },
        {
          id: 2,
          type: 'processing',
          status: true,
        },
        {
          id: 3,
          type: 'packed',
          status: false,
        },
        {
          id: 4,
          type: 'shipped',
          status: false,
        },
        {
          id: 5,
          type: 'delivered',
          status: false,
        },
      ],
      orderTrack: [
        {
          id: 1,
          title: 'Order Delivered',
          subTitle: 'Enjoy your product!',
          time: 11.15,
          status: true,
        },
        {
          id: 2,
          title: 'Order Dispatched',
          subTitle: 'Contact Rider',
          time: 11.1,
          status: true,
        },
        {
          id: 3,
          title: 'Order Confirmed',
          subTitle: 'Awaiting confirmation',
          time: 11.1,
          status: true,
        },
        {
          id: 4,
          title: 'Order Placed',
          subTitle: 'Thank you for ordering',
          time: 10.04,
          status: true,
        },
        // {
        //   id: 5,
        //   title: 'Order Placed',
        //   subTitle: 'We have received your order',
        //   time: 10.04,
        //   status: true,
        // },
      ],
    },
    {
      orderId: 'GM2D36-54',
      status: 'Delivered',
      date: 'Thus 25, Jun 2022',
      totallItems: 15,
      grandTotall: 3560,
      deliveryTime: 'Jun 25 -  06:30PM',
      deliveryLocation:
        'Harvest Group, DITF Bangladesh 14 Pavilion Golen, Dhaka-1212',
      orderItems: [
        {
          id: 1,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 2,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/breakfast.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 3,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 4,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
      ],
      orderView: [
        {
          id: 1,
          type: 'confirmed',
          status: true,
        },
        {
          id: 2,
          type: 'processing',
          status: true,
        },
        {
          id: 3,
          type: 'packed',
          status: true,
        },
        {
          id: 4,
          type: 'shipped',
          status: true,
        },
        {
          id: 5,
          type: 'delivered',
          status: true,
        },
      ],
      orderTrack: [
        {
          id: 1,
          title: 'Order Delivered',
          subTitle: 'Enjoy your product!',
          time: 11.15,
          status: true,
        },
        {
          id: 2,
          title: 'Order Dispatched',
          subTitle: 'Contact Rider',
          time: 11.1,
          status: true,
        },
        {
          id: 3,
          title: 'Order Confirmed',
          subTitle: 'Awaiting confirmation',
          time: 11.1,
          status: true,
        },
        {
          id: 4,
          title: 'Order Placed',
          subTitle: 'Thank you for ordering',
          time: 10.04,
          status: true,
        },
        // {
        //   id: 5,
        //   title: 'Order Placed',
        //   subTitle: 'We have received your order',
        //   time: 10.04,
        //   status: true,
        // },
      ],
    },
    {
      orderId: 'GM2D36-55',
      status: 'Pending',
      date: 'Thus 25, Jun 2022',
      totallItems: 15,
      grandTotall: 3560,
      deliveryTime: 'Jun 25 -  06:30PM',
      deliveryLocation:
        'Harvest Group, DITF Bangladesh 14 Pavilion Golen, Dhaka-1212',
      orderItems: [
        {
          id: 1,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 2,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/breakfast.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 3,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
        {
          id: 4,
          name: 'Product Name can be long',
          price: 899,
          discount_price: 699,
          image: require('../assets/images/firstList/vegetable.png'),
          discountRate: 29,
          qty: 2,
        },
      ],
      orderView: [
        {
          id: 1,
          type: 'confirmed',
          status: true,
        },
        {
          id: 2,
          type: 'processing',
          status: true,
        },
        {
          id: 3,
          type: 'packed',
          status: true,
        },
        {
          id: 4,
          type: 'shipped',
          status: false,
        },
        {
          id: 5,
          type: 'delivered',
          status: false,
        },
      ],
      orderTrack: [
        {
          id: 1,
          title: 'Order Delivered',
          subTitle: 'Enjoy your product!',
          time: 11.15,
          status: true,
        },
        {
          id: 2,
          title: 'Order Dispatched',
          subTitle: 'Contact Rider',
          time: 11.1,
          status: true,
        },
        {
          id: 3,
          title: 'Order Confirmed',
          subTitle: 'Awaiting confirmation',
          time: 11.1,
          status: true,
        },
        {
          id: 4,
          title: 'Order Placed',
          subTitle: 'Thank you for ordering',
          time: 10.04,
          status: true,
        },
        // {
        //   id: 5,
        //   title: 'Order Placed',
        //   subTitle: 'We have received your order',
        //   time: 10.04,
        //   status: true,
        // },
      ],
    },
  ];